system:
  default:
    server:
      port: 4201
    eureka:
      hostname: localhost
      port: 8761
    datasource:
      hostname: localhost
      port: 3306
      database: eShop
      username: eShop
      password: sicher

spring:
  profiles: default
  application:
    name: authentication-service
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://${system.default.datasource.hostname}:${system.default.datasource.port}/${system.default.datasource.database}?useSSL=false
    username: ${system.default.datasource.username}
    password: ${system.default.datasource.password}

server:
  port: ${PORT:${system.default.server.port}}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${system.default.eureka.hostname}:${system.default.eureka.port}/eureka/
  instance:
    preferIpAddress: true