system:
  eureka:
    hostname: localhost
    port: 8761

spring:
  profiles: default
  application:
    name: catalog-service

server:
  port: 5001

eureka:
  client:
    serviceUrl:
      defaultZone: http://${system.eureka.hostname}:${system.eureka.port}/eureka/
  instance:
    preferIpAddress: true
    appname: ${spring.application.name}