system:
  docker:
    server:
      port: ${CONTAINER_CATALOG_PORT}
    eureka:
      hostname: ${CONTAINER_EUREKA_NAME}
      port: ${CONTAINER_EUREKA_PORT}
  default:
    server:
      port: 5001
    eureka:
      hostname: localhost
      port: 8761

---

spring:
  profiles: default
  application:
    name: catalog-service

server:
  port: ${PORT:${system.default.server.port}}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${system.default.eureka.hostname}:${system.default.eureka.port}/eureka/
  instance:
    preferIpAddress: true
    appname: ${spring.application.name}
    metadataMap:
          instanceId: "${spring.application.name}:${random.value}"

ribbon:
  readTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
---

spring:
  profiles: docker-container
  application:
      name: catalog-service

server:
  port: ${PORT:${system.docker.server.port}}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${system.docker.eureka.hostname}:${system.docker.eureka.port}/eureka/
  instance:
    preferIpAddress: true
