system:
  eureka:
    hostname: localhost
    port: 8761

spring:
  profiles: default
  application:
    name: catalog-service

server:
  port: 5001

CatalogService:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:5002, localhost:5003, localhost:5004, localhost:5005
    ServerListRefreshInterval: 15000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${system.eureka.hostname}:${system.eureka.port}/eureka/
  instance:
    preferIpAddress: true
    appname: ${spring.application.name}