system:
  eureka:
    port: 8761

server:
  port: ${PORT:${system.eureka.port}}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
    prefer-ip-address: true

